# Generated by Django 4.2.19 on 2025-02-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_surveyresult_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.CharField(max_length=255, unique=True)),
                ('serialized_model', models.BinaryField()),
            ],
        ),
    ]
